services:
  db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: Afpa1234
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3307:3306

  web:
    build: .
    ports:
      - 8000:8000
    volumes:
      - .:/var/www

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
    ports:
      - 8080:80

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025
      - 8025:8025

volumes:
  data:
    driver: local
